# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 100

  - name: About
    url: about/
    weight: 200

  - name: Project
    url: test/
    weight: 300
  - parent: Project
    name: OhMyPosh
    url: /use
    weight: 310
  - parent: Project
    name: test1-2
    url: /
    weight: 310

  - name: Test2
    url: /test
    weight: 400
  # - parent: Test2
  #   name: test2-1
  #   url: /
  #   weight: 410
  # - parent: Test2
  #   name: test2-2
  #   url: /
  #   weight: 410

  - name: Noification
    url: /notification
    weight: 500
  # - parent: Test3
  #   name: test3-1
  #   url: /
  #   weight: 510
  # - parent: Test3
  #   name: test3-2
  #   url: /
  #   weight: 510

  - name: Use
    url: /use
    weight: 600

  - name: Contact
    url: /contact
    weight: 700

